apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-monolito
  labels:
    app: api-monolito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-monolito
  template:
    metadata:
      labels:
        app: api-monolito
    spec:
      containers:
      - name: api-monolito
        image: gcr.io/impactful-shard-476618-j9/api-monolito:v1
        ports:
        - containerPort: 13000
        env:
        - name: SERVER_PORT
          value: "13000"
        - name: POSTGRES_URL
          value: "jdbc:postgresql://136.112.152.217:5432/postgres"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-password
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongo-uri
        - name: ALLOWED_ORIGINS
          value: "*"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 13000
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 13000
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-monolito-service
spec:
  selector:
    app: api-monolito
  ports:
  - port: 80
    targetPort: 13000
    protocol: TCP
  type: LoadBalancer
