apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=  # postgres
  postgres-password: NEBPYU9BUEx2fXYwKFQxaQ==  # 4@OaOAPLv}v0(T1i
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  jwt-secret: c2VjcmV0LTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA=  # secret-0000000000000000000000000000
  mongo-uri: bW9uZ29kYitzcnY6Ly9TMTM6bWp0YkF2bm9CUlM5TURBcUBtb25vbGl0by53cnZjNGNsLm1vbmdvZGIubmV0L21vbm9saXRvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPW1vbm9saXRv  # sua URI do MongoDB Atlas
