apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  postgres-user: cG9zdGdyZXM=  # postgres
  postgres-password: ***REMOVED***  # 4@OaOAPLv}v0(T1i
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  jwt-secret: ***REMOVED***  # secret-0000000000000000000000000000
  mongo-uri: ***REMOVED***  # sua URI do MongoDB Atlas
