CREATE TABLE tb_ambiente
(
    id_ambiente BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    nm_ambiente VARCHAR(80)                             NOT NULL,
    tp_local    VARCHAR(20)                             NOT NULL,
    is_ativo    BOOLEAN,
    CONSTRAINT pk_tb_ambiente PRIMARY KEY (id_ambiente)
);

CREATE TABLE tb_composicao_ambiente
(
    id_composicao_ambiente BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    id_padrao              BIGINT                                  NOT NULL,
    id_item_ambiente       BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_composicao_ambiente PRIMARY KEY (id_composicao_ambiente)
);

CREATE TABLE tb_composicao_material
(
    id_composicao_material BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    id_padrao              BIGINT                                  NOT NULL,
    id_marca_material      BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_composicao_material PRIMARY KEY (id_composicao_material)
);

CREATE TABLE tb_empreendimento
(
    id_empreendimento BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    nm_empreendimento VARCHAR(80)                             NOT NULL,
    tp_status         VARCHAR(20)                             NOT NULL,
    id_padrao         BIGINT,
    CONSTRAINT pk_tb_empreendimento PRIMARY KEY (id_empreendimento)
);

CREATE TABLE tb_item_ambiente
(
    id_item_ambiente BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    id_item_desc     BIGINT                                  NOT NULL,
    id_ambiente      BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_item_ambiente PRIMARY KEY (id_item_ambiente)
);

CREATE TABLE tb_item_desc
(
    id_item_desc BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    nm_item_desc VARCHAR(120),
    is_ativo     BOOLEAN,
    ds_item      VARCHAR(320)                            NOT NULL,
    id_item_type BIGINT,
    CONSTRAINT pk_tb_item_desc PRIMARY KEY (id_item_desc)
);

CREATE TABLE tb_item_type
(
    id_item_type BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    nm_item_type VARCHAR(60)                             NOT NULL,
    is_ativo     BOOLEAN,
    CONSTRAINT pk_tb_item_type PRIMARY KEY (id_item_type)
);

CREATE TABLE tb_marca
(
    id_marca   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    nm_marca   VARCHAR(80)                             NOT NULL,
    is_ativo   BOOLEAN,
    CONSTRAINT pk_tb_marca PRIMARY KEY (id_marca)
);

CREATE TABLE tb_marca_material
(
    id_marca_material BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    id_marca          BIGINT                                  NOT NULL,
    id_material       BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_marca_material PRIMARY KEY (id_marca_material)
);

CREATE TABLE tb_material
(
    id_material BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    nm_material VARCHAR(80)                             NOT NULL,
    is_ativo    BOOLEAN,
    CONSTRAINT pk_tb_material PRIMARY KEY (id_material)
);

CREATE TABLE tb_padrao
(
    id_padrao  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    nm_padrao  VARCHAR(80)                             NOT NULL,
    is_ativo   BOOLEAN,
    CONSTRAINT pk_tb_padrao PRIMARY KEY (id_padrao)
);

CREATE TABLE tb_processo_historico
(
    id_processo_historico BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_empreendimento     BIGINT,
    id_revisao            BIGINT,
    tp_acao               VARCHAR(20)                             NOT NULL,
    id_processo_origem    BIGINT,
    id_bin                BIGINT,
    dt_comeco             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dt_fim                TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_processo_historico PRIMARY KEY (id_processo_historico)
);

CREATE TABLE tb_revisao
(
    id_revisao   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    tp_status    VARCHAR(20)                             NOT NULL,
    ds_conclusao VARCHAR(240),
    tp_regra     VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_tb_revisao PRIMARY KEY (id_revisao)
);

CREATE TABLE tb_usuario_empreendimento
(
    id_usuario_empreendimento BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    updated_at                TIMESTAMP WITHOUT TIME ZONE,
    id_usuario                BIGINT                                  NOT NULL,
    id_empreendimento         BIGINT                                  NOT NULL,
    tp_access                 VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_tb_usuario_empreendimento PRIMARY KEY (id_usuario_empreendimento)
);

ALTER TABLE tb_composicao_material
    ADD CONSTRAINT uc_08b8943936c4b7c55a3d4e6bd UNIQUE (id_padrao, id_marca_material);

ALTER TABLE tb_marca_material
    ADD CONSTRAINT uc_13b90d2d6e7c6538b37dc19af UNIQUE (id_marca, id_material);

ALTER TABLE tb_item_desc
    ADD CONSTRAINT uc_42ec6fa16e85f02b30788ddfc UNIQUE (nm_item_desc, ds_item, id_item_type);

ALTER TABLE tb_composicao_ambiente
    ADD CONSTRAINT uc_6b14a62b49df76f22a2f3fb3b UNIQUE (id_padrao, id_item_ambiente);

ALTER TABLE tb_ambiente
    ADD CONSTRAINT uc_af11dd7fdd8402ea11cb9d88c UNIQUE (nm_ambiente, tp_local);

ALTER TABLE tb_item_ambiente
    ADD CONSTRAINT uc_b5345cbb2931d8c9274e64ef4 UNIQUE (id_item_desc, id_ambiente);

ALTER TABLE tb_processo_historico
    ADD CONSTRAINT uc_c5321692490bc43fbd65ba99a UNIQUE (id_empreendimento, id_revisao, id_processo_origem);

ALTER TABLE tb_empreendimento
    ADD CONSTRAINT uc_tb_empreendimento_nm_empreendimento UNIQUE (nm_empreendimento);

ALTER TABLE tb_item_type
    ADD CONSTRAINT uc_tb_item_type_nm_item_type UNIQUE (nm_item_type);

ALTER TABLE tb_padrao
    ADD CONSTRAINT uc_tb_padrao_nm_padrao UNIQUE (nm_padrao);

ALTER TABLE tb_composicao_ambiente
    ADD CONSTRAINT FK_TB_COMPOSICAO_AMBIENTE_ON_ID_ITEM_AMBIENTE FOREIGN KEY (id_item_ambiente) REFERENCES tb_item_ambiente (id_item_ambiente);

ALTER TABLE tb_composicao_ambiente
    ADD CONSTRAINT FK_TB_COMPOSICAO_AMBIENTE_ON_ID_PADRAO FOREIGN KEY (id_padrao) REFERENCES tb_padrao (id_padrao);

ALTER TABLE tb_composicao_material
    ADD CONSTRAINT FK_TB_COMPOSICAO_MATERIAL_ON_ID_MARCA_MATERIAL FOREIGN KEY (id_marca_material) REFERENCES tb_marca_material (id_marca_material);

ALTER TABLE tb_composicao_material
    ADD CONSTRAINT FK_TB_COMPOSICAO_MATERIAL_ON_ID_PADRAO FOREIGN KEY (id_padrao) REFERENCES tb_padrao (id_padrao);

ALTER TABLE tb_empreendimento
    ADD CONSTRAINT FK_TB_EMPREENDIMENTO_ON_ID_PADRAO FOREIGN KEY (id_padrao) REFERENCES tb_padrao (id_padrao) ON DELETE SET NULL;

ALTER TABLE tb_item_ambiente
    ADD CONSTRAINT FK_TB_ITEM_AMBIENTE_ON_ID_AMBIENTE FOREIGN KEY (id_ambiente) REFERENCES tb_ambiente (id_ambiente);

ALTER TABLE tb_item_ambiente
    ADD CONSTRAINT FK_TB_ITEM_AMBIENTE_ON_ID_ITEM_DESC FOREIGN KEY (id_item_desc) REFERENCES tb_item_desc (id_item_desc);

ALTER TABLE tb_item_desc
    ADD CONSTRAINT FK_TB_ITEM_DESC_ON_ID_ITEM_TYPE FOREIGN KEY (id_item_type) REFERENCES tb_item_type (id_item_type) ON DELETE SET NULL;

ALTER TABLE tb_marca_material
    ADD CONSTRAINT FK_TB_MARCA_MATERIAL_ON_ID_MARCA FOREIGN KEY (id_marca) REFERENCES tb_marca (id_marca);

ALTER TABLE tb_marca_material
    ADD CONSTRAINT FK_TB_MARCA_MATERIAL_ON_ID_MATERIAL FOREIGN KEY (id_material) REFERENCES tb_material (id_material);

ALTER TABLE tb_processo_historico
    ADD CONSTRAINT FK_TB_PROCESSO_HISTORICO_ON_ID_EMPREENDIMENTO FOREIGN KEY (id_empreendimento) REFERENCES tb_empreendimento (id_empreendimento) ON DELETE SET NULL;

ALTER TABLE tb_processo_historico
    ADD CONSTRAINT FK_TB_PROCESSO_HISTORICO_ON_ID_PROCESSO_ORIGEM FOREIGN KEY (id_processo_origem) REFERENCES tb_processo_historico (id_processo_historico);

ALTER TABLE tb_processo_historico
    ADD CONSTRAINT FK_TB_PROCESSO_HISTORICO_ON_ID_REVISAO FOREIGN KEY (id_revisao) REFERENCES tb_revisao (id_revisao) ON DELETE CASCADE;

CREATE TABLE tb_papel
(
    id_papel   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    nm_papel   VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_tb_papel PRIMARY KEY (id_papel)
);

CREATE TABLE tb_usuario
(
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    nm_usuario VARCHAR(100)                            NOT NULL,
    ds_senha   VARCHAR(255)                            NOT NULL,
    ds_email   VARCHAR(100),
    fk_papel   BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_usuario PRIMARY KEY (id_usuario)
);

ALTER TABLE tb_usuario
    ADD CONSTRAINT FK_TB_USUARIO_ON_FK_PAPEL FOREIGN KEY (fk_papel) REFERENCES tb_papel (id_papel);

ALTER TABLE tb_usuario_empreendimento
    ADD CONSTRAINT FK_TB_USUARIO_EMPREENDIMENTO_ON_ID_EMPREENDIMENTO FOREIGN KEY (id_empreendimento) REFERENCES tb_empreendimento (id_empreendimento);

ALTER TABLE tb_usuario_empreendimento
    ADD CONSTRAINT FK_TB_USUARIO_EMPREENDIMENTO_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES tb_usuario (id_usuario);

ALTER TABLE tb_papel
    ADD CONSTRAINT uc_tb_papel_nm_papel UNIQUE (nm_papel);

ALTER TABLE tb_material
    ADD CONSTRAINT uc_tb_material_nm_material UNIQUE (nm_material);

ALTER TABLE tb_marca
    ADD CONSTRAINT uc_tb_marca_nm_marca UNIQUE (nm_marca);