server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-monolito
  config:
    import: file:.env.dev.properties

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://admin:admin@localhost:27017/monolito?authSource=admin}

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/monolito}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: false

  flyway:
    enabled: false
    baseline-on-migrate: false
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /api-docs

api:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5000}