CREATE TABLE tb_ambiente
(
    id_ambiente BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_ambiente VARCHAR(40)                             NOT NULL,
    is_ativo    BOOLEAN,
    CONSTRAINT pk_tb_ambiente PRIMARY KEY (id_ambiente)
);

CREATE TABLE tb_ambiente_padrao
(
    id_ambiente  BIGINT NOT NULL,
    id_padrao    BIGINT NOT NULL,
    is_ativo     BOOLEAN,
    associationa BIGINT NOT NULL,
    associationb BIGINT NOT NULL,
    CONSTRAINT pk_tb_ambiente_padrao PRIMARY KEY (associationa, associationb)
);

CREATE TABLE tb_item
(
    id_item      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_item      VARCHAR(40)                             NOT NULL,
    is_ativo     BOOLEAN,
    tipo_item_id BIGINT,
    vl_largura   VARCHAR(20),
    vl_altura    VARCHAR(20),
    ds_item      VARCHAR(60),
    CONSTRAINT pk_tb_item PRIMARY KEY (id_item)
);

CREATE TABLE tb_item_ambiente
(
    id_item_composto BIGINT NOT NULL,
    id_ambiente      BIGINT NOT NULL,
    is_ativo         BOOLEAN,
    associationa     BIGINT NOT NULL,
    associationb     BIGINT NOT NULL,
    CONSTRAINT pk_tb_item_ambiente PRIMARY KEY (associationa, associationb)
);

CREATE TABLE tb_item_composto
(
    id_item_composto BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_item          BIGINT                                  NOT NULL,
    id_material      BIGINT,
    id_marca         BIGINT,
    is_ativo         BOOLEAN,
    CONSTRAINT pk_tb_item_composto PRIMARY KEY (id_item_composto)
);

CREATE TABLE tb_marca
(
    id_marca BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_marca VARCHAR(40)                             NOT NULL,
    is_ativo BOOLEAN,
    CONSTRAINT pk_tb_marca PRIMARY KEY (id_marca)
);

CREATE TABLE tb_material
(
    id_material BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_material VARCHAR(40)                             NOT NULL,
    is_ativo    BOOLEAN,
    CONSTRAINT pk_tb_material PRIMARY KEY (id_material)
);

CREATE TABLE tb_padrao
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_padrao VARCHAR(50)                             NOT NULL,
    is_ativo  BOOLEAN,
    CONSTRAINT pk_tb_padrao PRIMARY KEY (id)
);

CREATE TABLE tb_tipo_item
(
    id_tipo_item BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_tipo_item VARCHAR(40)                             NOT NULL,
    is_ativo     BOOLEAN,
    CONSTRAINT pk_tb_tipo_item PRIMARY KEY (id_tipo_item)
);

ALTER TABLE tb_ambiente
    ADD CONSTRAINT uc_tb_ambiente_nm_ambiente UNIQUE (nm_ambiente);

ALTER TABLE tb_item
    ADD CONSTRAINT uc_tb_item_nm_item UNIQUE (nm_item);

ALTER TABLE tb_marca
    ADD CONSTRAINT uc_tb_marca_nm_marca UNIQUE (nm_marca);

ALTER TABLE tb_material
    ADD CONSTRAINT uc_tb_material_nm_material UNIQUE (nm_material);

ALTER TABLE tb_padrao
    ADD CONSTRAINT uc_tb_padrao_nm_padrao UNIQUE (nm_padrao);

ALTER TABLE tb_tipo_item
    ADD CONSTRAINT uc_tb_tipo_item_nm_tipo_item UNIQUE (nm_tipo_item);

ALTER TABLE tb_ambiente_padrao
    ADD CONSTRAINT FK_TB_AMBIENTE_PADRAO_ON_ID_AMBIENTE FOREIGN KEY (id_ambiente) REFERENCES tb_ambiente (id_ambiente);

ALTER TABLE tb_ambiente_padrao
    ADD CONSTRAINT FK_TB_AMBIENTE_PADRAO_ON_ID_PADRAO FOREIGN KEY (id_padrao) REFERENCES tb_padrao (id);

ALTER TABLE tb_item_ambiente
    ADD CONSTRAINT FK_TB_ITEM_AMBIENTE_ON_ID_AMBIENTE FOREIGN KEY (id_ambiente) REFERENCES tb_ambiente (id_ambiente);

ALTER TABLE tb_item_ambiente
    ADD CONSTRAINT FK_TB_ITEM_AMBIENTE_ON_ID_ITEM_COMPOSTO FOREIGN KEY (id_item_composto) REFERENCES tb_item_composto (id_item_composto);

ALTER TABLE tb_item_composto
    ADD CONSTRAINT FK_TB_ITEM_COMPOSTO_ON_ID_ITEM FOREIGN KEY (id_item) REFERENCES tb_item (id_item);

ALTER TABLE tb_item_composto
    ADD CONSTRAINT FK_TB_ITEM_COMPOSTO_ON_ID_MARCA FOREIGN KEY (id_marca) REFERENCES tb_marca (id_marca);

ALTER TABLE tb_item_composto
    ADD CONSTRAINT FK_TB_ITEM_COMPOSTO_ON_ID_MATERIAL FOREIGN KEY (id_material) REFERENCES tb_material (id_material);

ALTER TABLE tb_item
    ADD CONSTRAINT FK_TB_ITEM_ON_TIPO_ITEM FOREIGN KEY (tipo_item_id) REFERENCES tb_tipo_item (id_tipo_item);