DROP TABLE IF EXISTS tb_item_ambiente CASCADE;
DROP TABLE IF EXISTS tb_marca_material CASCADE;
DROP TABLE IF EXISTS tb_item CASCADE;
DROP TABLE IF EXISTS tb_marca CASCADE;
DROP TABLE IF EXISTS tb_material CASCADE;
DROP TABLE IF EXISTS tb_ambiente CASCADE;
DROP TABLE IF EXISTS tb_padrao CASCADE;
DROP TABLE IF EXISTS tb_ambiente_padrao CASCADE;
DROP TABLE IF EXISTS tb_item_composto CASCADE;
DROP TABLE IF EXISTS tb_tipo_item CASCADE;

CREATE TABLE IF NOT EXISTS tb_ambiente
(
    id_ambiente BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_ambiente VARCHAR(80)                             NOT NULL,
    tp_local    VARCHAR(20)                             NOT NULL,
    is_ativo    BOOLEAN,
    CONSTRAINT pk_tb_ambiente PRIMARY KEY (id_ambiente)
);

CREATE TABLE IF NOT EXISTS tb_item
(
    id_item  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_item  VARCHAR(80)                             NOT NULL,
    is_ativo BOOLEAN,
    ds_item  VARCHAR(240)                             NOT NULL,
    CONSTRAINT pk_tb_item PRIMARY KEY (id_item)
);

CREATE TABLE IF NOT EXISTS tb_item_ambiente
(
    is_obrigatorio BOOLEAN,
    id_item        BIGINT NOT NULL,
    id_ambiente    BIGINT NOT NULL,
    CONSTRAINT pk_tb_item_ambiente PRIMARY KEY (id_item, id_ambiente)
);

CREATE TABLE IF NOT EXISTS tb_marca
(
    id_marca BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_marca VARCHAR(80)                             NOT NULL,
    is_ativo BOOLEAN,
    CONSTRAINT pk_tb_marca PRIMARY KEY (id_marca)
);

CREATE TABLE IF NOT EXISTS tb_marca_material
(
    is_obrigatorio BOOLEAN,
    id_marca       BIGINT NOT NULL,
    id_material    BIGINT NOT NULL,
    CONSTRAINT pk_tb_marca_material PRIMARY KEY (id_marca, id_material)
);

CREATE TABLE IF NOT EXISTS tb_material
(
    id_material BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_material VARCHAR(80)                             NOT NULL,
    is_ativo    BOOLEAN,
    CONSTRAINT pk_tb_material PRIMARY KEY (id_material)
);

ALTER TABLE tb_ambiente
    ADD CONSTRAINT uc_tb_ambiente_nm_ambiente UNIQUE (nm_ambiente);

ALTER TABLE tb_item
    ADD CONSTRAINT uc_tb_item_nm_item UNIQUE (nm_item);

ALTER TABLE tb_marca
    ADD CONSTRAINT uc_tb_marca_nm_marca UNIQUE (nm_marca);

ALTER TABLE tb_material
    ADD CONSTRAINT uc_tb_material_nm_material UNIQUE (nm_material);

ALTER TABLE tb_item_ambiente
    ADD CONSTRAINT FK_TB_ITEM_AMBIENTE_ON_ID_AMBIENTE FOREIGN KEY (id_ambiente) REFERENCES tb_ambiente (id_ambiente);

ALTER TABLE tb_item_ambiente
    ADD CONSTRAINT FK_TB_ITEM_AMBIENTE_ON_ID_ITEM FOREIGN KEY (id_item) REFERENCES tb_item (id_item);

ALTER TABLE tb_marca_material
    ADD CONSTRAINT FK_TB_MARCA_MATERIAL_ON_ID_MARCA FOREIGN KEY (id_marca) REFERENCES tb_marca (id_marca);

ALTER TABLE tb_marca_material
    ADD CONSTRAINT FK_TB_MARCA_MATERIAL_ON_ID_MATERIAL FOREIGN KEY (id_material) REFERENCES tb_material (id_material);