DROP TABLE IF EXISTS tb_item_ambiente CASCADE;
DROP TABLE IF EXISTS tb_marca_material CASCADE;
DROP TABLE IF EXISTS tb_item CASCADE;
DROP TABLE IF EXISTS tb_marca CASCADE;
DROP TABLE IF EXISTS tb_material CASCADE;
DROP TABLE IF EXISTS tb_ambiente CASCADE;
DROP TABLE IF EXISTS tb_padrao CASCADE;
DROP TABLE IF EXISTS tb_ambiente_padrao CASCADE;
DROP TABLE IF EXISTS tb_item_composto CASCADE;
DROP TABLE IF EXISTS tb_tipo_item CASCADE;

CREATE TABLE tb_ambiente (
    id_ambiente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_ambiente VARCHAR(40) NOT NULL,
    is_ativo    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uc_tb_ambiente_nm_ambiente UNIQUE (nm_ambiente)
);

CREATE TABLE tb_item (
     id_item  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     nm_item  VARCHAR(40) NOT NULL,
     ds_item  VARCHAR(60) NOT NULL,
     is_ativo BOOLEAN NOT NULL DEFAULT TRUE,
     CONSTRAINT uc_tb_item_nm_item UNIQUE (nm_item)
);

CREATE TABLE tb_marca (
    id_marca BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_marca VARCHAR(40) NOT NULL,
    is_ativo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uc_tb_marca_nm_marca UNIQUE (nm_marca)
);

CREATE TABLE tb_material (
    id_material BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nm_material VARCHAR(40) NOT NULL,
    is_ativo    BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uc_tb_material_nm_material UNIQUE (nm_material)
);

CREATE TABLE tb_item_ambiente (
      id_item        BIGINT NOT NULL,
      id_ambiente    BIGINT NOT NULL,
      is_obrigatorio BOOLEAN NOT NULL DEFAULT FALSE,
      CONSTRAINT pk_tb_item_ambiente PRIMARY KEY (id_item, id_ambiente),
      CONSTRAINT fk_tb_item_ambiente_on_item
          FOREIGN KEY (id_item) REFERENCES tb_item (id_item),
      CONSTRAINT fk_tb_item_ambiente_on_ambiente
          FOREIGN KEY (id_ambiente) REFERENCES tb_ambiente (id_ambiente)
);

CREATE TABLE tb_marca_material (
    id_marca       BIGINT NOT NULL,
    id_material    BIGINT NOT NULL,
    is_obrigatorio BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_tb_marca_material PRIMARY KEY (id_marca, id_material),
    CONSTRAINT fk_tb_marca_material_on_marca
       FOREIGN KEY (id_marca) REFERENCES tb_marca (id_marca),
    CONSTRAINT fk_tb_marca_material_on_material
       FOREIGN KEY (id_material) REFERENCES tb_material (id_material)
);