-- V4__criar_usuario_e_papel.sql

CREATE TABLE tb_papel
(
    id_papel BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_papel VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_tb_papel PRIMARY KEY (id_papel)
);

ALTER TABLE tb_papel
    ADD CONSTRAINT uc_tb_papel_nm_papel UNIQUE (nm_papel);


CREATE TABLE tb_usuario
(
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_usuario VARCHAR(100)                            NOT NULL,
    ds_email   VARCHAR(100),
    ds_senha   VARCHAR(255)                            NOT NULL,
    fk_papel   BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_usuario PRIMARY KEY (id_usuario)
);

ALTER TABLE tb_usuario
    ADD CONSTRAINT uc_tb_usuario_nm_usuario UNIQUE (nm_usuario);

ALTER TABLE tb_usuario
    ADD CONSTRAINT uc_tb_usuario_ds_email UNIQUE (ds_email);

ALTER TABLE tb_usuario
    ADD CONSTRAINT FK_TB_USUARIO_ON_FK_PAPEL FOREIGN KEY (fk_papel) REFERENCES tb_papel (id_papel);


-- 3. POPULANDO PAPÉIS INICIAIS
-- Estes papéis devem corresponder ao seu enum Role (ADMIN, REVISOR, RELATOR)
INSERT INTO tb_papel (nm_papel)
VALUES ('ADMIN');
INSERT INTO tb_papel (nm_papel)
VALUES ('REVISOR');
INSERT INTO tb_papel (nm_papel)
VALUES ('RELATOR');

-- 4. POPULANDO UM USUÁRIO ADMINISTRADOR DE TESTE
-- SENHA: 123456 (BCRYPT ENCODE)
-- Hash gerado com BCrypt com cost=10.
-- Usuario: admin
-- Senha: 123456
INSERT INTO tb_usuario (nm_usuario, ds_email, ds_senha, fk_papel)
VALUES ('admin',
        'admin@empresa.com',
        '$2a$10$tdMmaawF8ysX6noQLlnO.OBabkT3VgofjRE.oWnU3VnVcTnu4zVzm', -- Hash para '123456'
        (SELECT id_papel FROM tb_papel WHERE nm_papel = 'ADMIN'));