-- ITEM
ALTER TABLE tb_item DROP CONSTRAINT uc_tb_item_nm_item;
ALTER TABLE tb_item ADD CONSTRAINT uc_tb_item_nm_item_ds_item UNIQUE (nm_item, ds_item);

INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rodapé', 'Porcelanato ou Laminado, h=5cm.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Peitoril', 'Metálico ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rodapé', 'Vinílico, mármore, granito ou madeira, h=5cm.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede externa', 'Textura acrílica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Tabeira', 'Mármore ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Hidráulico', 'Torneira em PVC rígido.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Ar Condicionado', 'Infraestrutura para high wall com condensadora axial.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede', 'Textura Acrílica ou Pastilha Cerâmica, conforme definido em projeto arquitetônico.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rodapé', 'Porcelanato ou Laminado, h= 5cm', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Vinílico.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Borda', 'Mármore ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Bancada ', 'Mármore ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Esquadria', 'Alumínio pintado de branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rede de Água', 'Rede de água interligada ao sistema público de fornecimento de água tratada, alimentando reservatório inferior.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede', 'Cerâmica até o teto.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Gradil', 'Em perfil metálico pintado de branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Equipamentos', 'Bomba e filtro da Jacuzzi, Mark Peerles ou similar, e dispositivos em aço inox ou PVC.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Pintura acrílica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede Interna', 'Pintura PVA látex branco sobre gesso ou massa de regulariação PVA. Acima das bancadas será aplicado revestimento cerâmico. Nas demais paredes textura acrílica ou pintura acrílica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Porta', 'Alumínio pintado de branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Porta', 'Porta semi–ôca comum pintada c/ esmalte sintético.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Pintura PVA látex branco sobre gesso ou massa de regulariação PVA ou Forro em gesso.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Metais', 'Torneiras e registro de gaveta com acabamento cromado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Porcelanato ou laminado', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rede elétrica', 'Rede aérea ou subterrânea.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Porta', 'Porta semi-ôca comum pintura c/ esmalte sintético.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Ferragem', 'Acabamento cromado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétrica', 'Ponto de luz no teto.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Comunic.', 'Tubulação seca.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Vidro', 'Liso incolor.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Pintura látex PVA sobre gesso ou argamassa de regularização PVA.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Porcelanato ou laminado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede interna', 'Pintura PVA látex.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Comunicação', 'Tubulação seca.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Portão', 'Metálico pintado de branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede Externa', 'Acabamento em textura acrílica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Passeio', 'Em concreto com junta seca.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Cuba', 'Inox.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Pintura PVA látex branco sobre gesso ou massa de regulariação PVA.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Porta externa', 'Alumínio pintado na cor branca com vidro liso.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Equipamentos', 'A serem definidos.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Jardins', 'Grama e alguns arbustos em locais definidos no projeto.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Hidráulica', 'Engate, sifão, rede de água fria e esgoto em PVC.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso (Piscina)', 'Pastilha cerâmica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso Deck', 'Porcelanato Incesa, Lef, Incefra, Portobello ou Cecafi, ou pedra natural.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede', 'Fechamento em tela de nylon ou alambrado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Fechamento', 'Tela alambrado ou tela de proteção.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Hidráulica', 'Rede de água fria em PEX e esgoto em PVC', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Esquadria', 'Alumínio printado de branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Cerâmica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede', 'Textura acrílica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Peitoril', 'Metálico', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Em concreto desempolado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Cordão de Box', 'Mármore ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Comunic.', 'Pontos secos de comunicação e de antena de TV.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Tampo do balcão', 'Mármore ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Porcelanato', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Pintura PVA látex branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Cobogó', 'Em concreto.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rede de comunicação', 'Rede subterrânea ou aérea com tubulação seca e shafts ao longo dos pavimentos.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétrica', 'Pontos de luz no teto, tomadas de corrente e interruptores.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Bancada', 'Em mármore ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede', 'Pintura PVA látex branco sobre gesso ou massa de regulariação PVA.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Esquadria', 'Alumínio pintado de branco', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede (Piscina)', 'Pastilha cerâmica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Metal Sanitário', 'Torneira para Lavatório, registro de gaveta e registro de pressão com acabamento cromado .', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Forro de gesso.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto ', 'Pintura PVA látex branco sobre gesso ou massa de regulariação PVA ou Forro de gesso.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Churrasqueira', 'Pré-moldada ou alvenaria.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Esgot. Sanitário', 'Rede interna lançando no sistema público de coleta de esgoto ou Estação de Tratamento de Esgoto de operação do condomínio.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rodapé', 'Porcelanato ou Laminado, h= 5cm.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Metais', 'Torneira para pia com acabamento cromado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Porta', 'Alumínio pintado de branco com vidro liso.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede', 'Cerâmica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede interna', 'Cerâmica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rodapé', 'Porcelanato, h=5cm.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Bancada', 'Em mármore ou granito com cuba em louça cor branca', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rodapé', 'Cerâmica, h=5cm.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Peitoril', 'Metálico.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Pintura PVA látex branco sobre gesso ou massa de regulariação PVA ou forro de gesso.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétricas ', 'Ponto de luz no teto com luminária.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Vidro', 'Liso.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Brinquedos', 'A serem definidos.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Ferragens', 'Acabamento cromado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Equipamentos', 'A serem definidos', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Pintura PVA látex branco sobre gesso ou massa de regularização PVA.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede', 'Pintura acrílica ou textura acrílica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede Interna', 'Pintura PVA látex branco sobre gesso ou massa de regulariação PVA.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétrica', 'Pontos de luz no teto, tomada de corrente e interruptor da Prime, Alumbra, Cemar ou Fame na cor branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rodapé', 'Cerâmica, h=5 cm.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Concreto desempolado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Tanque', 'Louça cor branca.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Soleira', 'Mármore ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Louças', 'Vaso Sanitário com Caixa Acoplada em louça cor branca.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétricas', 'Ponto de luz no teto, tomadas de corrente e interruptores.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Intertravado emborrachado ou grama.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Vidro ', 'Pontilhado Incolor.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Esquadrias', 'Alumínio pintado de branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Drenag./pluviais', 'Através de caixas com lançamento em rede existente.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Pavimentação', 'Piso intertravado de concreto ou paralelepípedo sobre colchão de areia.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Parede', 'Pintura PVA látex branco sobre gesso ou massa de regularização PVA. Acima das bancadas será aplicado revestimento cerâmico. Nas demais paredes textura acrílica ou pintura acrílica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Filete', 'Mármore ou granito L=3,5cm.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Rodapé', 'Porcelanato, h=5 cm.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Iluminação das ruas', 'Braços com Lâmpadas instalados nos postes da concessionária de energia ou em postes exclusivos para iluminação.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Ferragens', 'Com acabamento cromado.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétrica', 'Pontos de luz no teto, tomadas de corrente e interruptores', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétricas ', 'Ponto de luz no teto com luminária e interruptor na cor branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Porcelanato.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Acabamento Interno', 'Bloco cerâmico rebocado e pintado ou bloco de concreto aparente.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétricas ', 'Ponto de luz no teto com luminária, tomada de corrente e interruptor na cor branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Tampo do Balcão', 'Mármore ou granito.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Guarda Corpo', 'Em perfil metálico pintado de branco.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Hidráulica', 'Sifão em PVC, esgoto em PVC, rede de água fria e ducha higiênica em PEX.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Teto', 'Pintura ou textura acrílica.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Grama', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Vidro ', 'Liso incolor.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Acabamento Externo', 'Bloco cerâmico rebocado e pintura ou bloco cerâmico com chapisco rústico ou bloco de concreto aparente.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Piso', 'Concreto.', TRUE);
INSERT INTO tb_item (nm_item, ds_item, is_ativo) VALUES ('Inst. Elétrica', 'Fechadura elétrica no portão para pedestres, e motor para acionamento do portão para veículos.', TRUE);

-- MATERIAL
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Cuba (louça)', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Cerâmica', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Porta (alumínio)', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Metal Sanitário', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Ferragem', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Esquadria', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Louças', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Cuba (inox)', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Laminado', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Inst. Elétrica', TRUE);
INSERT INTO tb_material (nm_material, is_ativo) VALUES ('Porcelanato', TRUE);

-- MARCA
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Lef', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Papaiz', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Camelo Fior', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Incesa', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Eliane', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Portobello', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Soprano', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Margirius', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Arouca', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Mgm', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Tramontina', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Pianox', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Steck', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Ceusa', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Meber', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Atlantica', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Alumasa', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Stam', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Kelly', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Roca', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Tecnocuba', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Incepa', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('La Fonte', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Deca', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Aliança', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Ramassol', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Unicasa', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Pointer', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Eucatex', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Fabrimar', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Arielle', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Pamesa', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Durafloor', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Espaçofloor', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Ilumi', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Mari Louças', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Ideal', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Icasa', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Villagres', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Alumbra', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Peesa – Una Max', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Ghel Plus', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Esaf', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Portinari', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Fame', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Forusi', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Logasa', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Elizabeth', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Biancogrês', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Imab', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Tecnogres', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Esteves', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Talita', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Pado', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Silvana', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Celite', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Schneider', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Frank', TRUE);
INSERT INTO tb_marca (nm_marca, is_ativo) VALUES ('Docol', TRUE);

-- AMBIENTE
ALTER TABLE tb_ambiente DROP CONSTRAINT uc_tb_ambiente_nm_ambiente;
ALTER TABLE tb_ambiente ADD CONSTRAINT uc_tb_ambiente_nm_ambiente_tp_local UNIQUE (nm_ambiente, tp_local);

INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Sanitário/ Lavabo', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Quiosques', 'ÁREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Quadra de Areia', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Circulação', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Gourmets', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Gourmets', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Brinquedoteca', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Gerador', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Guarita', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Depósito (DML)', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Portão de veículos (externo)', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Administração', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Passeio externo', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Vestiário Feminino/ Masculino', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Sala de Estar/Jantar', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Garden', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Quadra Esportiva', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Muro de fechamento do condomínio', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Quarto e Suíte', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Cozinha/ Área de Serviço', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Petplay', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Salão de jogos', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Parque Infantil', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Varanda', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Copa Funcionários', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Casa de lixo', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Área Técnica', 'UNIDADES_PRIVATIVAS', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Instalações Gerais', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Salão de Festas', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Academia', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Vias internas e estacionamentos das unidades', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Jardins', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Bicicletário', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Piscina Adulto/ Infantil/ Deck', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Escadaria das torres', 'AREA_COMUM', TRUE);
INSERT INTO tb_ambiente (nm_ambiente, tp_local, is_ativo) VALUES ('Hall’s do lazer e torres', 'AREA_COMUM', TRUE);
