CREATE TABLE tb_empreendimento
(
    id_empreendimento BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nm_empreendimento VARCHAR(80)                             NOT NULL,
    tp_status         VARCHAR(20)                             NOT NULL,
    id_padrao         BIGINT,
    CONSTRAINT pk_tb_empreendimento PRIMARY KEY (id_empreendimento)
);

CREATE TABLE tb_revisao
(
    id_revisao        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tp_status         VARCHAR(20)                             NOT NULL,
    id_empreendimento BIGINT                                  NOT NULL,
    CONSTRAINT pk_tb_revisao PRIMARY KEY (id_revisao)
);

CREATE TABLE tb_usuario_empreendimento
(
    id_usuario_empreendimento BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario                BIGINT                                  NOT NULL,
    id_empreendimento         BIGINT                                  NOT NULL,
    tp_access                 VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_tb_usuario_empreendimento PRIMARY KEY (id_usuario_empreendimento)
);

ALTER TABLE tb_empreendimento
    ADD CONSTRAINT uc_tb_empreendimento_nm_empreendimento UNIQUE (nm_empreendimento);

ALTER TABLE tb_empreendimento
    ADD CONSTRAINT FK_TB_EMPREENDIMENTO_ON_ID_PADRAO FOREIGN KEY (id_padrao) REFERENCES tb_padrao (id_padrao) ON DELETE SET NULL;

ALTER TABLE tb_revisao
    ADD CONSTRAINT uc_tb_revisao_id_empreendimento UNIQUE (id_empreendimento);

ALTER TABLE tb_revisao
    ADD CONSTRAINT FK_TB_REVISAO_ON_ID_EMPREENDIMENTO FOREIGN KEY (id_empreendimento) REFERENCES tb_empreendimento (id_empreendimento);

ALTER TABLE tb_usuario_empreendimento
    ADD CONSTRAINT FK_TB_USUARIO_EMPREENDIMENTO_ON_ID_EMPREENDIMENTO FOREIGN KEY (id_empreendimento) REFERENCES tb_empreendimento (id_empreendimento);

ALTER TABLE tb_usuario_empreendimento
    ADD CONSTRAINT FK_TB_USUARIO_EMPREENDIMENTO_ON_ID_USUARIO FOREIGN KEY (id_usuario) REFERENCES tb_usuario (id_usuario);