CREATE TABLE tb_processo_historico
(
    id_processo_historico BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_empreendimento     BIGINT,
    id_revisao            BIGINT,
    tp_acao               VARCHAR(20)                             NOT NULL,
    id_processo_origem    BIGINT,
    dt_comeco             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    dt_fim                TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tb_processo_historico PRIMARY KEY (id_processo_historico)
);

ALTER TABLE tb_processo_historico
    ADD CONSTRAINT uc_c5321692490bc43fbd65ba99a UNIQUE (id_empreendimento, id_revisao, id_processo_origem);

ALTER TABLE tb_processo_historico
    ADD CONSTRAINT FK_TB_PROCESSO_HISTORICO_ON_ID_EMPREENDIMENTO FOREIGN KEY (id_empreendimento) REFERENCES tb_empreendimento (id_empreendimento) ON DELETE SET NULL;

ALTER TABLE tb_processo_historico
    ADD CONSTRAINT FK_TB_PROCESSO_HISTORICO_ON_ID_PROCESSO_ORIGEM FOREIGN KEY (id_processo_origem) REFERENCES tb_processo_historico (id_processo_historico);

ALTER TABLE tb_processo_historico
    ADD CONSTRAINT FK_TB_PROCESSO_HISTORICO_ON_ID_REVISAO FOREIGN KEY (id_revisao) REFERENCES tb_revisao (id_revisao) ON DELETE CASCADE;

ALTER TABLE tb_revisao
    DROP CONSTRAINT fk_tb_revisao_on_id_empreendimento;

ALTER TABLE tb_revisao
    ADD dt_atualizacao TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE tb_revisao
    ADD dt_criacao TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE tb_revisao
    ADD tp_regra VARCHAR(20);

ALTER TABLE tb_revisao
    ALTER COLUMN dt_criacao SET NOT NULL;

ALTER TABLE tb_revisao
    ALTER COLUMN tp_regra SET NOT NULL;

ALTER TABLE tb_revisao
    DROP COLUMN created_at;

ALTER TABLE tb_revisao
    DROP COLUMN id_empreendimento;

ALTER TABLE tb_revisao
    DROP COLUMN tp_rule;

ALTER TABLE tb_revisao
    DROP COLUMN updated_at;